### PR TITLE
Publish to npm?

### PR DESCRIPTION
**Pull request by queckezz**
Would be awesome! Didn't came up with a better name that hasn't already been taken

### CODE REVIEW

**Comment by bredele** [comment]
@queckezz it's always a pain to find a name on npm :p

**Comment by bredele** [comment]
@queckezz found one...let me know what you think

**Comment by queckezz** [comment]
Great ;) I normally don't like using undescriptive names that doesn't resemble the purpose of the module. But since we're living in a global namespace theres not much you can do anyway :P

**Comment by bredele** [comment]
Nop :) you can use namespaces in your package.json (bredele/curry) and it will fetch the module on github but it won't be registered to npmjs.

**Pull request closed without merging**
